### ISSUE TITLE
Text and HTML should be defaulted to null-like value, not an empty object/or array

### ISSUE THREAD

**Issue by fosron** [mailersend/mailersend-ruby#1]
https://github.com/mailersend/mailersend-ruby/blob/b791c89396568ea648dd102dfe668ab2017745eb/lib/mailersend/email/email.rb#L31-L32

I do think that these lines can be interpreted by Ruby and sent through JSON to our API as an empty `object` or `array`. And in a case where a `template_id` is provided, and it has default settings, these are not required and are introducing an error.

This theory should be tested, however.

This is an example that breaks on the API side:

<img width="1329" alt="Screenshot 2021-08-02 at 10 58 38" src="https://user-images.githubusercontent.com/3708631/127871179-aa13b487-c302-47b6-9852-6c46f00b3c87.png">

**Comment by fosron** [comment]
These empty values should not be sent:

```json
{
   "attachments": [],
   "bcc": [],
   "cc": [],
   "from": [],
   "html": [],
   "personalization": [],
   "reply_to": [],
   "template_id": "id",
   "text": [],
   "to": [
      {
         "email": "john@test.com",
         "name": "John"
      }
   ],
   "variables": []
}
```

**Comment by nklmilojevic** [comment]
I can see why it could fail - will try to reproduce it and fix it in the SDK. Also it should be validated on the API side so we have both client and server side validation. 

Will tackle it this week.

**Comment by nklmilojevic** [comment]
Version 0.2.1 pushed which has a fix for this https://rubygems.org/gems/mailersend-ruby/versions/0.2.1
