### ISSUE TITLE
Configurable `API_TOKEN`

### ISSUE THREAD

**Issue by verdywid** [mailersend/mailersend-ruby#3]
### Expected behavior
Makes the `API_TOKEN` configurable through config file, hence the env variable name can be anything

### Actual behavior
The only way to set the token now is through env variable, which might clash with another environment variable with the same name

**Comment by nklmilojevic** [comment]
@verdywid Apologies for waiting. For now, we have renamed API_TOKEN to MAILERSEND_API_TOKEN thanks to @fullmetalengineer. Please update the gem to the latest version:

https://github.com/mailersend/mailersend-ruby/releases/tag/v1.0.0
