### ISSUE TITLE
Tags not being added in template emails

### ISSUE THREAD

**Issue by marcelkooi** [mailersend/mailersend-ruby#40]
There is the `add_tags` method in the [MailerSend::Email](https://github.com/mailersend/mailersend-ruby/blob/7c4372999eaed61498d7d2fba83a4e05944c3c90/lib/mailersend/email/email.rb#L85-L87) class but it does not seem to add tags to the email.

If you take the readme example code and add:

```rb
...
ms_email.add_tags('test-tag')

# Send the email
ms_email.send
```

It will not add a tag to the email.

Thanks!

**Comment by dinomh** [comment]
Thanks for pointing it out 🙏 Version 1.3.2 now contains a fix for this: https://rubygems.org/gems/mailersend-ruby

**Comment by marcelkooi** [comment]
@dinomh No problem and thanks for the quick turnaround!
