### ISSUE TITLE
Inadequate documentation for reply_to feature in sending mails

### ISSUE THREAD

**Issue by Kaushik-Iyer** [mailersend/mailersend-ruby#75]
The documentation at https://developers.mailersend.com/api/v1/email.html#send-an-email does not specify any Limitations or details for the reply_to attribute while sending an email. After testing the ruby sdk multiple times, I think that the reply_to field only takes one value at a time, and on sending multiple values, it keeps on overwriting the previous value. This should be mentioned in the documentation I feel. I am ready to contribute in this way, since I also use the mailersend ruby sdk on a daily basis, but I couldn't find the documentation repository.

**Comment by dinomh** [comment]
The `reply_to` field in MailerSend's email API only supports one email address at a time. If you try to include multiple values in the `reply_to` field, the last value will simply overwrite any previous ones. We will update this in our docs.
